name: Deploy to production

on:
  release:
    types:
      - created

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_ENV: production
      REPOSITORY: registry.digitalocean.com/getequity

    steps:
      - uses: actions/checkout@v2

      - name: Get Repository Name
        run: echo "SERVICE_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Update SHA
        run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/_meta

      - name: Build image
        run: docker build -t $REPOSITORY/$SERVICE_NAME:$(echo $GITHUB_SHA | head -c7) .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: docker push $REPOSITORY/$SERVICE_NAME:$(echo $GITHUB_SHA | head -c7)

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl k8s cluster kubeconfig show ${{ secrets.CLUSTER_NAME }} > .kubeconfig

      - name: Deploy to DigitalOcean Kubernetes
        run: helm --debug upgrade --install $SERVICE_NAME ./helm --kubeconfig=.kubeconfig --namespace=$APP_ENV --set image.repository=$REPOSITORY/$SERVICE_NAME,image.tag=$(echo $GITHUB_SHA | head -c7)
